name: Des
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  snosey_flutter_package: ^0.8.5
  shared_preferences: ^2.0.8
  font_awesome_flutter: ^9.2.0
  flutter_staggered_grid_view: ^0.4.1
  provider: ^6.0.1
#  syncfusion_flutter_charts: ^19.3.57
  flutter_datetime_picker: ^1.5.1
  json_annotation: ^4.3.0
  get: ^4.3.8
  fluttertoast: ^8.0.8
  timeago: ^3.1.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0

  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.12
  connectivity: ^3.0.6
  #Dont update
  file_picker: ^4.0.2
  syncfusion_flutter_datepicker: ^24.1.46
  flutter_riverpod: ^2.4.9
  flutter_zoom_drawer: ^3.1.1
  video_compress: ^3.1.2
  lottie: ^2.7.0
  dinnova:
    git:
      url: https://github.com/D-Innova/dinnova_flutter_package.git
      ref: main


dependency_overrides:
  intl: ^0.18.0
  file_picker: ^6.1.1
  syncfusion_flutter_xlsio: ^24.1.46



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: any

flutter:
  uses-material-design: true
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo_Light.ttf
        - asset: assets/fonts/Cairo_Bold.ttf
          weight: 900

  assets:
    - assets/images/
    - assets/animation/

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true